export default {
  SPEED_WORLD_DOWN: 10,
  EXTRA_Y_WORD: 0.5,
  TIME_ADD_WORD: 4000,
  INIT_WORDS: [
    "interact",
    "personnel",
    "resources department",
    "job application",
    "temporary position",
    "specify",
    "a period of",
    "go on maternity leave",
    "satisfied",
    "possibility",
    "direction",
    "reschedule",
    "feel free to call me",
    "permanent",
    "meantime",
    "various",
    "corporate",
    "detail oriented",
    "meet strict deadlines",
    "hesitate",
    "candidate",
    "eye for decorating",
    "balcony",
    "piled",
    "shelves",
    "put sth away",
    "bending",
    "filing cabinet",
    "hill",
    "stair",
    "intend",
  ],
};
